// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyGoiLea-LAAiEbff5lT8eXn4TIEYrsOY',
    appId: '1:392843798473:web:329a2e5495ddaf0ed52a18',
    messagingSenderId: '392843798473',
    projectId: 'nova-liga-sul-ba541',
    authDomain: 'nova-liga-sul-ba541.firebaseapp.com',
    storageBucket: 'nova-liga-sul-ba541.appspot.com',
    measurementId: 'G-88EZWBNPPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApsgqR5IRHqMvwv-4IBPNLcjX06_ANQYI',
    appId: '1:392843798473:android:b14015fd1029445cd52a18',
    messagingSenderId: '392843798473',
    projectId: 'nova-liga-sul-ba541',
    storageBucket: 'nova-liga-sul-ba541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqp4yNucGN1HsGfBqfFYWlwaOSTPmouLI',
    appId: '1:392843798473:ios:d533e608bb08bbc2d52a18',
    messagingSenderId: '392843798473',
    projectId: 'nova-liga-sul-ba541',
    storageBucket: 'nova-liga-sul-ba541.appspot.com',
    iosClientId: '392843798473-9l8lac0tkpst963sdq4pm7ula197b0ub.apps.googleusercontent.com',
    iosBundleId: 'com.example.novaLigaSul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqp4yNucGN1HsGfBqfFYWlwaOSTPmouLI',
    appId: '1:392843798473:ios:d533e608bb08bbc2d52a18',
    messagingSenderId: '392843798473',
    projectId: 'nova-liga-sul-ba541',
    storageBucket: 'nova-liga-sul-ba541.appspot.com',
    iosClientId: '392843798473-9l8lac0tkpst963sdq4pm7ula197b0ub.apps.googleusercontent.com',
    iosBundleId: 'com.example.novaLigaSul',
  );
}
